name: Run Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: create proxy conf
      - uses: KotKompot0/github-set-proxy-conf-angular@v0.1.0
        with:
          path: "./proxy.conf.json"
          target: "https://www.timeapi.io/api"
          url: "/api"
          secure: "true"
          pathRewriteOld: "^/api"
          pathRewriteNew: "empty"
          changeOrigin: "true"
          logLevel: "null"
          type: "create"
      - name: Run tests
        run: |
          yarn run test --browsers ChromeHeadless --watch=false
